### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by guozijing** [qingwave/mycni#3]
Hi, 大佬，你这有点错，删除ip 的时候也会新建store，dataDir 已经存在，会报错，需要加个判断是否存在
dir := filepath.Join(dataDir, network)
if err := os.MkdirAll(dir, 0755); err != nil {
     return nil, err
}

**Comment by qingwave** [comment]
欢迎提交PR :smile:

**Comment by guozijing** [comment]
大佬你这是故意留的漏洞  给大家机会吗 哈哈哈

**Comment by qingwave** [comment]
> 大佬你这是故意留的漏洞 给大家机会吗 哈哈哈

这个建议倒是不错

**Comment by qingwave** [comment]
Fixed by #4
