### ISSUE TITLE
mycni 和 mycnid 重复创建 Bridge

### ISSUE THREAD

**Issue by mayooot** [qingwave/mycni#5]
在 mycnid 的 [NewReconciler](https://github.dev/qingwave/mycni/blob/c74e7bfb205333582601f2b0cde40313c7a05dcd/cmd/mycnid/main.go#L190-L192) 中创建了自定义网桥。而在 mycni 的[cmdAdd](https://github.dev/qingwave/mycni/blob/c74e7bfb205333582601f2b0cde40313c7a05dcd/cmd/mycni/main.go#L54-L57) 也创建了网桥。

Flannel 插件的流程图里，好像只有在调用 CNI 二进制文件时才创建网桥（如果不存在）。
那么为啥 mycni 和 mycnid 都创建了呢，希望可以解答一下。
![image](https://github.com/qingwave/mycni/assets/85121496/a8de3c45-e71e-46a8-9396-658bb44cbeb5)

**Comment by qingwave** [comment]
Good question, 很久前写的了，看了下代码，应该是为了保证`mycnid`在初始化iptables网桥一定存在，去掉创建网桥的代码应该也是可以正常工作的。

**Comment by mayooot** [comment]
> Good question, 很久前写的了，看了下代码，应该是为了保证`mycnid`在初始化iptables网桥一定存在，去掉创建网桥的代码应该也是可以正常工作的。

原理如此，谢谢解答😊
